import json
import ast
import os
import logging
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from ..database import get_db
from ..models.models import User, File as FileModel, Scan, Report
from ..security.auth import get_current_user

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/reports", tags=["Reports"])


def _parse_json_list(value):
    """Parse a JSON list column, falling back to Python literal syntax for legacy data."""
    if not value:
        return []
    if isinstance(value, (list, tuple)):
        return list(value)
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, list) else []
    except (json.JSONDecodeError, TypeError):
        try:
            parsed = ast.literal_eval(value)
            return parsed if isinstance(parsed, list) else []
        except (ValueError, SyntaxError, TypeError):
            return []


def _pdf_safe(value):
    """Coerce any value to a string that the PDF's latin-1 core fonts can encode."""
    if not isinstance(value, str):
        value = str(value)
    return value.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf_report(scan, file_record, output_path: str) -> str:
    """Generate a PDF report for a scan result using fpdf2."""
    from fpdf import FPDF, XPos

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Malicious File Detection Report", ln=True, align="C")
    pdf.ln(5)

    # Report metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}", ln=True)
    pdf.cell(0, 8, f"Scan ID: {scan.id}", ln=True)
    pdf.ln(5)

    # Separator
    pdf.set_draw_color(0, 0, 0)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # File Information
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "File Information", ln=True)
    pdf.set_font("Helvetica", "", 10)

    file_info = [
        ("Original Filename", file_record.original_filename if file_record else "N/A"),
        ("File Size", f"{file_record.file_size} bytes" if file_record else "N/A"),
        ("MD5", file_record.md5 if file_record else "N/A"),
        ("SHA-1", file_record.sha1 if file_record else "N/A"),
        ("SHA-256", file_record.sha256 if file_record else "N/A"),
        ("MIME Type", file_record.mime_type if file_record else "N/A"),
        ("Extension", file_record.extension if file_record else "N/A"),
    ]

    for label, value in file_info:
        pdf.cell(50, 7, f"{label}:", ln=False)
        pdf.cell(0, 7, _pdf_safe(value), ln=True)

    pdf.ln(5)

    # Scan Results
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Scan Results", ln=True)
    pdf.set_font("Helvetica", "", 10)

    classification = (scan.classification or "unknown").upper()
    if classification == "MALICIOUS":
        pdf.set_text_color(220, 20, 20)
    elif classification == "SUSPICIOUS":
        pdf.set_text_color(255, 140, 0)
    else:
        pdf.set_text_color(0, 128, 0)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(50, 7, "Classification:", ln=False)
    pdf.cell(0, 7, classification, ln=True)
    pdf.set_text_color(0, 0, 0)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(50, 7, "Risk Score:", ln=False)
    pdf.cell(0, 7, f"{scan.risk_score}/100", ln=True)
    pdf.cell(50, 7, "Entropy:", ln=False)
    pdf.cell(0, 7, f"{scan.entropy:.4f}", ln=True)
    pdf.cell(50, 7, "Scan Date:", ln=False)
    scan_date = scan.scan_date.strftime("%Y-%m-%d %H:%M:%S") if scan.scan_date else "N/A"
    pdf.cell(0, 7, scan_date, ln=True)

    if scan.vt_positives:
        pdf.cell(50, 7, "VirusTotal:", ln=False)
        pdf.cell(0, 7, f"{scan.vt_positives} detections", ln=True)

    pdf.ln(5)

    # Detection Reasons
    reasons = _parse_json_list(scan.detection_reasons)

    if reasons:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "Detection Reasons", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for reason in reasons:
            pdf.multi_cell(0, 7, _pdf_safe(f"- {reason}"), new_x=XPos.LMARGIN)

    pdf.ln(5)

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 8, "This report was generated by the Malicious File Detection System.", ln=True, align="C")

    pdf.output(output_path)
    return output_path


@router.get("/{scan_id}")
def get_report(
    scan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate and download a PDF report for a scan."""
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")

    file_record = db.query(FileModel).filter(FileModel.id == scan.file_id).first()

    import tempfile
    temp_dir = tempfile.mkdtemp()
    output_path = os.path.join(temp_dir, f"report_scan_{scan_id}.pdf")

    try:
        generate_pdf_report(scan, file_record, output_path)

        report = Report(
            scan_id=scan.id,
            generated_by=current_user.id,
            report_path=output_path,
        )
        db.add(report)
        db.commit()

        def iter_file():
            with open(output_path, "rb") as f:
                yield from f

        return StreamingResponse(
            iter_file(),
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="scan_report_{scan_id}.pdf"'
            },
        )

    except Exception as e:
        logger.error(f"Failed to generate report: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate report: {str(e)}")
